version: '3.8'

services:
  api:
    image: ahsan125/fastapi
    depends_on:
      - postgres
    ports:
      - 80:8000
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 
    #  env_file/
    #   - ./.env
    environment:
    - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
    - DATABASE_PORT=${DATABASE_PORT}
    - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    - DATABASE_NAME=${DATABASE_NAME}
    - DATABASE_USERNAME=${DATABASE_USERNAME}
    - SECRET_KEY=${SECRET_KEY}
    - ALGORITHM=${ALGORITHM}
    - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}

      # ... other environment variables
    

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
















# version: '3.8'

# services:
#   api:
#     build: .
#     ports:
#       - "8000:8000"
#     volumes:
#       - "./:/usr/src/app"
#     environment:
#       DATABASE_HOSTNAME: postgres
#       # ... other environment variables
#     command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
#     depends_on:
#       - postgres

#   postgres:
#     image: postgres
#     environment:
#       POSTGRES_PASSWORD: password123
#       POSTGRES_DB: fastapi
#     volumes:
#       - postgres-db:/var/lib/postgresql/data

# volumes:
#   postgres-db: